spring:
  profiles:
    active: prod, saml
  data:
    rest:
      base-path: /rest
  jackson:
    default-property-inclusion: non-null
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: "jdbc:mysql://localhost:3306/nogorkrishi?useUnicode=yes&characterEncoding=UTF-8"
    username: root
    password: root
---

spring:
  profiles: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: true

saml:
  entityid: nogorkrishi-dev
  entitybaseurl: http://localhost:8080