spring:
  profiles:
    active: prod
  data:
    rest:
      base-path: /rest
  thymeleaf:
    cache: false
---

spring:
  profiles: prod
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: "jdbc:mysql://localhost:3306/nogorkrishi?useUnicode=yes&characterEncoding=UTF-8"
    username: root
    password: root