spring:
  profiles:
    active: dev, saml
  data:
    rest:
      base-path: /rest
  jackson:
    default-property-inclusion: non-null
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: "jdbc:mysql://localhost:3306/nogorkrishi?useUnicode=yes&characterEncoding=UTF-8"
    username: root
    password: root
  mail:
    default-encoding: UTF-8
    host: localhost
    port: 26
    properties:
      mail:
        debug: false
        smtp:
          debug: false
          auth: false
          starttls: false
    protocol: smtp
    test-connection: false
---

spring:
  profiles: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/nogorkrishi?useUnicode=yes&characterEncoding=UTF-8"
    username: root
    password: root1234
  mail:
    default-encoding: UTF-8
    host: mail.rhchrc.com
    username: ngtest@rhchrc.com
    password: NGTest1234!@
    port: 26
    properties:
      mail:
        debug: false
        smtp:
          debug: false
          auth: true
          starttls: false
    protocol: smtp
    test-connection: false
saml:
  entityid: nogorkrishi-dev
  entitybaseurl: http://localhost:8080