server:
  port: 8080
spring:
  profiles:
    active: dev, saml
  data:
    rest:
      base-path: /rest
  jackson:
    default-property-inclusion: non-null
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: "jdbc:mysql://localhost:3306/nogor6?useUnicode=yes&characterEncoding=UTF-8"
    username: root
    password: 
  mail:
    default-encoding: UTF-8
    host: localhost
    port: 25
    properties:
      mail:
        debug: false
        smtp:
          debug: false
          auth: false
          starttls: false
    protocol: smtp
    test-connection: false
---

spring:
  profiles: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/nogor6?useUnicode=yes&characterEncoding=UTF-8"
    username: root
    password: 